// app/layout.js
import "./globals.css";
import ConditionalNavbar from "@/components/ConditionalNavbar";
import Providers from "./providers";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <ConditionalNavbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
